### ISSUE TITLE
Doc link broken

### ISSUE THREAD

**Issue by estaub** [AnimaApp/animaapp.github.io#5]
At the top of https://animaapp.github.io/faq.html , the "Doc" link is broken, goes to non-existent https://animaapp.github.io/docs/v1/guide/  .

This is probably an important link for you because a browsing person is likely to hit the FAQ, then the doc - "oh, there's not really any doc, bye".

The Doc link from the Home page is correct.

**Comment by orarbel** [comment]
Thanks! Fixed!
